# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-07-08 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='top_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, unique=True, verbose_name='客户端号码')),
                ('score', models.IntegerField(default=0, verbose_name='分数')),
            ],
            options={
                'verbose_name': '分数以及排行信息',
                'verbose_name_plural': '分数以及排行信息',
            },
        ),
    ]
